= Anypoint Platform CLI 3.x
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: administration, api, organization, users, gateway, theme, cli

Anypoint Platform provides a scripting and command line tool for both Anypoint Platform and Anypoint Platform Private Cloud Edition.
The CLI supports both interactive shell and standard CLI modes, and works with:

* xref:exchange::index.adoc[Anypoint Exchange]
* xref:access-management::index.adoc[Access Management]
* xref:index.adoc[Runtime Manager] for Mule applications deployed to CloudHub (hosted by MuleSoft) and customer-hosted Mule runtimes
* xref:virtual-private-cloud.adoc[VPCs]
* xref:cloudhub-dedicated-load-balancer.adoc[Cloudhub load balancers]
* xref:2.x@api-manager::index.adoc[API Manager 2.x (Crowd Release)]
* xref:design-center::index.adoc[Design Center]

== Prerequisites

* Download and install NodeJS and NPM (Node package manager) on your system.
+
See the https://nodejs.org/en/download/[NodeJS download page].
* Download and install Git version management on your system.
+
See the https://git-scm.com/downloads[Git download site].


== Installation

Depending on the configuration of your system, you might need to run these commands using administrator credentials.

[source,text,linenums]
----
$ npm install -g anypoint-cli@latest
----

If the installation command fails with the following error, make sure that the Git client is installed on your computer and the git protocol is not blocked by your firewall or network:

[source,text,linenums]
----
fatal: read error: Invalid argument
----

If the git protocol is blocked, you can configure Git to use `https://` instead of `git://`:

[source,text,linenums]
----
git config --global url."https://".insteadOf git://
----


== Reference

Every instance of Anypoint-CLI takes any of the following options:

[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter |Description | Required
| `username` | Your Anypoint Platform username.

You can also pass this value using a the environment variable `export ANYPOINT_USERNAME=<name>` | Yes

| `password` | Your Anypoint Platform password.

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>` | Yes

| `organization` | Your organization within Anypoint Platform.

You can also pass this value using the environment variable `export ANYPOINT_ORG=<name>` | No

| `environment` | Your Anypoint environment.

You can also pass this value using the environment variable `export ANYPOINT_ENV=<name>` | No

| `host` | The host of your Anypoint Platform Installation. +
By default, this value points to +https://anypoint.mulesoft.com+. +
If you are using Anypoint Platform Private Cloud Edition make sure to pass the address where you are hosting the platform.
If you are using Anypoint Platform EU Cloud, make sure you pass your EU control plane URL.

You can also pass this value using a dedicated environment variable `ANYPOINT_HOST=<name>` | No

| `bearer` | Instead of passing your username and password, you can choose to pass the token for your account. +
You can get the token for your account by hitting the +https://anypoint.mulesoft.com/accounts/login+ endpoint with your username and password to get your bearer value.

Your session expires when the token bearer expires. +
If you send both username and password, and the token bearer, the CLI prioritizes the bearer login.
| No
|===

== Usage

=== Logging In

=== Credentials File

The recommended way of passing these options to your Anypoint Platform CLI installation is using the `credentials` file located inside the `~/.anypoint` directory, which is not automatically created during installation. Follow these steps to create your credentials file:

. Create a directory called `.anypoint` in the `~/` directory for Linux and OSx, or `C:\Users\USERNAME \` in Windows.
. Navigate to your `.anypoint` directory and create a blank file named `credentials` with the following structure:
+
[source,text,linenums]
----
{
 "default": {
  "username": "yourAnypointUserName",
  "password": "yourAnypointPassword",
  "organization": "",
  "environment": "",
  "host": ""
 },
 "otherProfile": {
  "username": "",
  "password": "",
  "organization": "",
  "environment": "",
  "host": ""
 }
}
----
Note that the `default` profile is used unless the `ANYPOINT_PROFILE` environment variable is set:
+
[source,text,linenums]
----
> export ANYPOINT_PROFILE="otherProfile"
> anypoint-cli
----

Then run the `anypoint-cli` command without any options:

[source,text,linenums]
----
> anypoint-cli
----

=== Dedicated Environment Variables

If you choose to pass the credentials when running `anypoint-cli`, pass both parameters as environment variables: `ANYPOINT_USERNAME` and `ANYPOINT_PASSWORD`.

[source,text,linenums]
----
> export ANYPOINT_USERNAME="username"
> export ANYPOINT_PASSWORD="password"
> anypoint-cli
----

=== CLI Options

As instructed above, the username and password parameters are required. However, if you choose to pass your username, Anypoint Platform CLI prompts for your password.

[source,text,linenums]
----
> anypoint-cli --username="user"
Password: ****
----

=== Passing Commands

After setting up a proper way to access Anypoint Platform from the CLI, you can start passing commands. +
See xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI 3.x List of Commands] for instructions on how to use them.

== Considerations

A few considerations to keep in mind while using Anypoint-CLI:

. Environment variables override credentials file parameters and Command line parameters override environment variables. +
If you don't pass a command line parameter, the default profile properties are used.
. If you don't set an environment, you will be automatically sent to `production`. +
. Your Anypoint session expires based on the *Default session timeout* configured in your xref:access-management::organization.adoc#manage-the-master-organization-s-settings[Master Organization's settings]. +
. Anypoint-CLI works with autocomplete. You can start typing the name of the command or parameter and hit `tab` for an autocomplete, or double tap `tab` for a list of all possible options.

== See Also

* xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
