= About Impaired Workers
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

CloudHub performs constant health checks on the underlying virtual machines where Mule applications are running. A worker is impaired when there is a hardware or software failure that negatively impacts the running application deployed on the worker. Examples of hardware and software failures include network unavailability, memory issues, server hardware failures, file corruption, and so on.

When a worker is impaired, CloudHub automatically attempts to restart the worker and relaunch the application. If a retry is successful, the underlying worker and the Mule application are recovered without requiring any further action.

[NOTE]
It may take up to five minutes for a worker to restart.

If five retry attempts fail, an application's status becomes `Failed` or `Unrecoverable Runtime Error`. In this situation, you must manually redeploy and restart the application.

== Scheduled Maintenance Activities

Cloudhub checks for scheduled maintenance activities on the worker instances running the Mule applications. These maintenance activities involve a reboot, stop/start, or retirement of the instances, causing a potential downtime for the running applications. To ensure that that does not happen, Cloudhub checks for these scheduled events and informs the customer well in advance via notification to restart their application with zero downtime.