= Troubleshooting the Runtime Manager Agent
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: agent, mule, servers, monitor, notifications, external systems, third party, get status, metrics

A `$MULE_HOME/bin/amc_debug` script is available to help you troubleshoot Runtime Manager Agent installation issues.

If you experience issues with the Runtime Manager Agent Plugin or with managing applications on Anypoint Platform, run this script and save the output before filing a support ticket.

When you run this script it collects the following information to help troubleshoot your issue:

. Discover Mule/agent JVM process
. Extract Thread dump (not forced if possible)
. Extract Heap dump
+
[CAUTION]
--
This step can cause delays in running applications.
--
+
. Extract machine generic data: Java version, CPU usage, Memory usage, Disk usage.
. Copy all logs
. Copy Runtime Manager Agent Configuration files
. ZIP all the information

After the script completes, you can find a .zip file in the folder `$MULE_HOME/bin` (with a name similar to `snapshot_201701021410.zip`) that you can send to MuleSoft's support engineers to help troubleshoot your issues.

== Connectivity Problems

If you have connectivity issues, check the JVM you are using. If you are using the IBM JVM, you must install the truststore manually since this truststore requires special parameters that are different from the Oracle JVM or OpenJDK.

For instructions, see xref:servers-create#the-ibm-jvm[The IBM JVM].

== Runtime Manager Agent Documentation Pages

* xref:installing-and-configuring-runtime-manager-agent.adoc[Installing Runtime Manager Agent]
* xref:runtime-manager-agent-architecture.adoc[Runtime Manager Agent Architecture]
* xref:administration-service.adoc[Administration Service]
* xref:managing-applications-and-domains.adoc[Managing Applications and Domains]
* xref:event-tracking.adoc[Event Tracking]
* xref:jmx-service.adoc[JMX Service]
* xref:runtime-manager-agent-notifications.adoc[Runtime Manager Agent Notifications]
* xref:extending-the-runtime-manager-agent.adoc[Extending the Runtime Manager Agent]
* xref:internal-handler-buffering.adoc[Internal Handler Buffering]
