= Troubleshooting the Runtime Manager Agent
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: agent, mule, servers, monitor, notifications, external systems, third party, get status, metrics

You can use the `$MULE_HOME/bin/amc_debug` script to collect information used by Support to troubleshoot Anypoint Runtime Manager agent installation issues. If you experience issues with the Runtime Manager agent plug-in or with managing applications on Anypoint Platform, run the script and save the output before filing a support ticket.

The `amc_debug` script performs the following:

. Discovers the Mule agent JVM process
. Extracts the thread dump (not forced if possible)
. Optionally extracts the heap dump (if you specify the `-heap` option)
+
This step can cause delays in running applications.
+
. Extracts the Java version, CPU usage, memory usage, and disk usage
. Copies all logs
. Copies Runtime Manager agent configuration files
. Archives all the information collected in a .zip file

== Run the amc_debug Script

To run the `amc_debug` script to collect information about the agent installation:

. Open a terminal window and change to the `$MULE_HOME/bin` folder.
. Run the script:
+
`./amc_debug`
+
Include the `-heap` option to extract the heap in addition to the other data.
+
After the script completes, the folder `$MULE_HOME/bin` contains a .zip file with a name similar to `snapshot_201910081712.zip`.
. Send the .zip file to MuleSoft support engineers.

== Connectivity Issues

If you experience connectivity issues, check the JVM you are using. If you are using the IBM JVM, you must install the truststore manually because this truststore requires different parameters than Oracle JVM or OpenJDK. See xref:servers-create.adoc#ibm-jvm[IBM JVM].

== See Also

* xref:installing-and-configuring-runtime-manager-agent.adoc[Installing Runtime Manager Agent]
* xref:event-tracking.adoc[Event Tracking]
* xref:runtime-manager-agent-notifications.adoc[Runtime Manager Agent Notifications]
* xref:extending-the-runtime-manager-agent.adoc[Extending the Runtime Manager Agent]
* xref:internal-handler-buffering.adoc[Internal Handler Buffering]
