= Uploading Certificates to a Dedicated Load Balancer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The certificate that you upload to your load balancer must be contained in one unencrypted, PEM-encoded file.

This file must contain the entire certificate chain ordered sequentially, for example: 

[%header,cols="30a,70a"]
|===
| Certificate | Example
| The Primary Certificate | -----BEGIN CERTIFICATE----- +
(Your Primary SSL certificate: your_domain_name.crt) +
-----END CERTIFICATE-----
| The Intermediate Certificate | -----BEGIN CERTIFICATE----- +
(Your Intermediate certificate: DigiCertCA.crt) +
-----END CERTIFICATE-----
|===

You don't need to include the root certificate in the certificate chain. However, make sure to include the ASCII armor in each certificate.

When creating the load balancer, you can upload an SSL endpoint using the xref:anypoint-platform-cli.adoc#cloudhub-load-balancer-create[cloudhub load-balancer create] command from the CLI. 

You can upload a new SSL endpoint to an existing load balancer using Runtime Manager or the xref:anypoint-platform-cli.adoc#cloudhub-load-balancer-ssl-endpoint-add[`cloudhub load-balancer ssl-endpoint add`] command from the CLI.

== See Also

* xref:lp-ssl-endpoints[Configure SSL Endpoints]
* xref:lb-create-arm.adoc[Create a Load Balancer (Runtime Manager)]
* xref:anypoint-platform-cli.adoc#cloudhub-load-balancer-create[cloudhub load balancer create]
* xref:anypoint-platform-cli.adoc#cloudhub-load-balancer-ssl-endpoint-add[cloudhub load-balancer ssl-endpoint add]
