= Create a Load Balancer (Anypoint Platform CLI)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can create a dedicated load balancer (DLB) using the Anypoint Platform CLI.

== Prerequisites

To create a load balancer:

* Ensure that you are an administrator in the organization where you are creating the DLB.
* Create an Anypoint Virtual Private Cloud (Anypoint VPC) instance in the organization where you want to create a DLB.
* Create at least one certificate and private key for your certificate.

== Create a Load Balancer

Use this command to create a DLB from the CLI:

----
cloudhub load-balancer create myVPC myLB_name example-com-crt.pem example-com-private.pem
----

This command specifies the VPC in which to create the DLB and the certificate and private keys that the DLB uses.


== See Also

* xref:anypoint-platform-cli.adoc#cloudhub-load-balancer-create[cloudhub load-balancer create]
* xref:lb-cert-upload.adoc[Adding Certificates]
* xref:access-management::index.adoc[Access Management]
* xref:index.adoc[Create a Load Balancer (Runtime Manager)]
