= To Create a Load Balancer (CloudHub API)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can create a dedicated load balancer using the CloudHub API.

== Prerequisites

To create a load balancer using the CloudHub API, ensure that you perform the following:

* Ensure that your profile is a a member of the administrator role of in the organization where you are creating the load balancer.
* Create a Virtual Private Cloud (VPC) in the organization where you want to create a load balancer.
* Create at least one certificate and private key for your certificate.

== Creating a Load Balancer

To create a load balancer from the CLI, use the `cloudhub load-balancer create`. This command enables you to specify the VPC where the load balancer is created. It also enables you to specify the certificate and private keys used by the load balancer.

To create a load balancer using the CloudHub API, use the following endpoints:

* `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/loadbalancers`
* `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/vpcs`

== See Also

* xref:runtime-manager-api.adoc[Runtime Manager API]
* xref:access-management::index.adoc[Access Management]
* xref:lb-cert-upload.adoc[About Uploading Certificates]
* xref:index.adoc[To Create a Load Balancer using Runtime Manager]