= Create a Load Balancer (Anypoint Platform CLI)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can create a dedicated load balancer using the Anypoint Platform CLI.

== Prerequisites

To create a load balancer, ensure that you perform the following:

* Ensure that you are an administrator in the organization where you are creating the load balancer.
* Create an Anypoint Virtual Private Cloud (Anypoint VPC) in the organization where you want to create a load balancer.
* Create at least one certificate and private key for your certificate.

== Create a Load Balancer

To create a load balancer from the CLI, use the `cloudhub load-balancer create`. This command enables you to specify the Anypoint VPC where the load balancer is created. It also enables you to specify the certificate and private keys used by the load balancer.


== See Also

* xref:anypoint-platform-cli-commands.adoc#cloudhub-load-balancer-create[cloudhub load-balancer create]
* xref:lb-cert-upload.adoc[Adding Certificates]
* xref:access-management::index.adoc[Access Management]
* xref:lb-create-arm.adoc[Create a Load Balancer (Runtime Manager)]
* xref:lb-create-api.adoc[Create a Load Balancer (CloudHub API)]
