= Configure SSL Endpoints and Certificates
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: cloudhub, runtime manager, arm, load balancing, ssl, two way tls,

A dedicated load balancer must have at least one certificate associated with it. To configure an SSL endpoint for your load balancer to serve to clients, provide a certificate and private key pair for your load balancer to serve to clients. 

A load balancer can have multiple and independent SSL endpoints, each identified by its server certificate common name.

== Requirements

To associate an SSL endpoint, you must provide:

* An unencrypted, PEM-encoded (Privacy-Enhanced Mail) certificate file.
* A second file containing the private key of your PEM certificate.
+
The private key file must be _passphraseless_.

== Create a Certificate File and Private Key with Openssl

You can create both an unencrypted, PEM-encoded certificate file and a private key using `openssl`. 

For example, to create a self-signed certificate and corresponding private key:

. Enter:
+
[source,json,linenums]
----
openssl req -newkey rsa:2048 -nodes -keyout example-com-private.pem -x509 -days 3000 -out example-com-crt.pem
----
. When prompted, enter the certificate information.


Alternatively, you can pass a certificate information configuration file to the `openssl` command.

For example, this certificate configuration file named `example-com.cfg` defines the DNS domain `example.com` that includes some SAN (Subject Alternate Names) for two Mule applications: `app1.example.com` and `app2.example.com`.

[source,json,linenums]
----
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no
[ req_distinguished_name ]
countryName                 = US
stateOrProvinceName         = California
localityName               = San Francisco
organizationName           = MuleSoft
commonName                 = example.com

[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = app1.example.com
DNS.2   = app2.example.com
----

=== Create a Wildcard Certificate

You can create a wildcard certificate, for example, to support any subdomain request to `example.com`, including `app1.example.com` and `app2.example.com`, as well as any future subdomain names.

To create a wildcard certificate that maps any subdomain name to `example.com`:

. Create a file that includes this configuration:
+
[source,json,linenums]
----
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
prompt = no
[ req_distinguished_name ]
countryName                 = US
stateOrProvinceName         = California
localityName               = San Francisco
organizationName           = MuleSoft
commonName                 = *.example.com
----

. Pass the certificate configuration file in an `openssl` command:
+
[source,json,linenums]
----
openssl req -newkey rsa:2048 -nodes -keyout example-com-private.pem -x509 -days 3000 -out example-com-crt.pem -config example-com.cfg
----

. Decrypt the private key using `openssl`:
+
[source,json,linenums]
----
openssl rsa -in example-com-private.pem -out example-com-private-decrypted.pem
----

== Configuring Certificates for Production

Typically, in a production environment, your certificate is signed by a valid Certificate Authority (CA).
Each SSL endpoint can have multiple CA certificates and CRLs (Certificate Revocation Lists). You must provide each of these certificates in a single unencrypted, PEM-encoded file. Ordering is not important for independent CA certificates, but certificates in a chain of trust must be concatenated together.


== See Also

* xref:lb-cert-upload.adoc[Uploading Certificates]
* xref:lb-cert-validation.adoc[Certificate Validation]
* xref:lb-whitelists.adoc[Whitelists]
* xref:lb-mapping-rules.adoc[Mapping Rules]
