= Servers, Server Groups, and Clusters
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use Runtime Manager to register and set up the properties of servers, server groups, and clusters that reside on-premises. After setting up a server, you can select it as the deployment target for your applications.

== Server Groups and Clusters

Both server groups and clusters run applications in multiple distributed nodes.  When using a server group, instances of the applications are completely isolated from each other. In a cluster configuration, the nodes are aware of one another and share common information and synchronize statuses.

== Alerts

You can set up email alerts so you are notified when certain events occur on your servers, such as a server being disconnected, or a server being removed from a cluster. Alerts can be linked to a specific server in a cluster or server group, or to all of the servers in the cluster or server group. 

== See Also

* xref:cluster-add-srv.adoc[Add a Server to a Cluster (Hybrid)]
* xref:server-group-add.adoc[Add a Server to a Server Group (Hybrid)]
* xref:alerts-on-runtime-manager.adoc[Alerts] 
* xref:runtime-manager-switch-env.adoc[Switch Environments Using Runtime Manager]
* xref:deploying-to-your-own-servers.adoc[Deploy Applications to Your Own Servers]
* xref:managing-deployed-applications.adoc[Managing Deployed Applications]
* xref:managing-applications-on-your-own-servers.adoc[Managing Applications on Your Own Servers]
* xref:mule-runtime::mule-high-availability-ha-clusters.adoc[Mule High Availability Clusters]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/arm-rest-services[Anypoint Platform REST APIs]
