= To Resolve Private Domains in Your Internal Network
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can specify custom private domains by adding the IP address and domain name for your network. +

. From Anypoint Platform, click *Runtime Manager*.
. In the left navigation, click *VPCs*.
. Select the row of the VPC to configure, then click *Manage VPC*.
. Select the *Internal DNS* tab.
. Click *Add New IP*, then enter the IP address of your internal DNS server.+
. Click *Add New DNS*, then enter the domain name of your internal DNS server. +
You only need to add the common portion of the domain name, for example: mulesoft.com.
. Click *Apply Changes*.
+
image::internal-dns-configuration[]

When resolving a domain name in your internal network, consider the following:

* The IP address you configure is for the DNS server of your internal network. It is not the IP address of the service you are connecting to.
* The maximum number of characters of all the domains you configure must not exceed 255 characters. For example, adding the domains mydomain1.com and mydomain2.com would require 28 characters. Each domain name consumes an additional character because in the DNS hierarchy all domains end with a "." characer.
* You should avoid entering hostnames to ensure that you do not exceed the 255 character limit.

== See Also

* xref:vpc-architecture-concept.adoc[About VPC Network Architecture]
