= To View Server Properties (Hybrid)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Manager enables you to view and configure properties in your Mule runtime environments. Runtime Manager displays two types of properties.

== Custom Properties

Custom properties enable you to define properties used by the JVM container of a mule runtime. Custom properties are defined as key/value pairs.

== Discovered Properties

Discovered properties are properties defined by the remote environment of the Mule runtime. These include environment and system properties of the machine where your Mule runtime is located.

You can view the following types of properties:

* JVM Arguments
* Environment Properties
* System Properties

Runtime Manager retrieves the values of these properties from the Runtime Manager Agent which queries the `System` Java class on the remote server. By default, Autodiscovery of remote server properties is disabled. You must click Enable Discovery to use this feature. After enabling this feature, Runtime Manager stores an encrypted version of these properties in its internal database.

To fully disable this feature, contact your customer success representative.

== Viewing Server Properties

To view custom and discovered properties, perform the following:

. From Anypoint Platform, select Runtime Manager.
. Click Servers.
. Select the server whose properties you want to view, then click Manage Server.
. Click the Properties tab.
. Click either Custom Properties or Discovered Properties.
+
Before you can view discovered properties, you must click Enable Discovery. When this feature is enabled, these properties are stored in encrypted form in the Runtime Manager internal database.

From the Properties tab, you can also search for properties or sort them by key, value, or property type.

== See Also

* xref:servers-properties-create.adoc[To Create Customer Server Properties]