= Shut Down, Restart, or Delete a Server (Hybrid)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In a hybrid deployment scenario, after creating a server, you can control its status from Runtime Manager.

. From the *Servers* page, select the server you want to control.
. In the information panel, click the server status label and choose the action you want to perform from the drop-down list. You can perform the following actions:
+
* *Shutdown*
* *Restart*
* *Delete*
* *Renew Certificate*

. Confirm that you want to perform the selected action.

After shutting down the server, you cannot restart it from Runtime Manager. You must manually restart the server on the machine where the Mule runtime engine is installed.

If an error occurs in Runtime Manager during server shutdown or restart, you must manually perform the action on the machine where the Mule runtime engine is installed. Ensure that you have access to this system.

== See Also

* xref:mule-runtime::starting-and-stopping-mule-esb.adoc[Starting and Stopping Mule]
* xref:servers-create.adoc[Create a Server]
* xref:servers-cert-renewal.adoc[Renew a Server Certificate]
