= Configure Server Properties (Hybrid)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Manager enables you to view and configure properties in your Mule environments. Runtime Manager displays two types of properties.

== Custom Properties

Custom properties enable you to define properties used by the JVM container of a Mule instance. Custom properties are defined as key/value pairs.

== Discovered Properties

Discovered properties are properties defined by the remote environment of the Mule instance. These properties include:

* JVM arguments
* Environment properties
* System properties

Runtime Manager retrieves the values of these properties from Runtime Manager agent which queries the `System` Java class on the remote server. 

By default, auto-discovery of remote server properties is disabled. To use this feature, click *Enable Auto-Discovery* to use this feature. After enabling this feature, Runtime Manager stores an encrypted version of these properties in its internal database.

To fully disable this feature, contact your MuleSoft customer success representative.

== View Server Properties

To view custom and discovered properties:

. From Anypoint Platform, select *Runtime Manager*.
. Click the *Servers* tab.
. Click the type, and then click *Manage Server*, *Manage Group*, or *Manage Cluster* button on the details pane.
. Click the *Properties* tab.
. Click either *Custom Properties* or *Discovered Properties*.
+
To view discovered properties, click *Enable Auto-Discovery*. The server state must be *Running* to auto-discover server properties.

From the *Properties* tab, you can:

* Search for properties.
* Create new properties.
* Edit existing properties. 

== See Also

* xref:servers-settings.adoc[Access Server Settings]
* xref:servers-properties-create.adoc[Create Custom Server Properties]
