= Renew a Server Certificate (Hybrid)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When registering a runtime in Runtime Manager, you must supply a certificate to ensure secure communications between Runtime Manager and the Runtime Manager Agent. When the certificate expires, you can renew it directly from Runtime Manager. You can update a certificate for a specific server or multiple servers within a cluster or group.

You can view the expiration date of the certificate from the server dashboard. To update a server certificate, the server status must be *Running*.

. From the *Servers* tab, select the server whose certificate you want to update.
. In the information panel, click the *Actions* button and select *Renew Certificate*.
. Click the checkbox to confirm, then click *Renew*.

To verify that the certificate was successfully renewed, check the value of *Certificate expiration* in the server dashboard.

== See Also

* xref:servers-about.adoc[About Servers (Hybrid)]
* xref:servers-actions.adoc[Shutdown, Restart, and Delete a Server (Hybrid)]