= Troubleshoot Transit Gateway Attachments
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

These are some of the possible errors you might encounter when attempting to attach to a transit gateway.

== Unable to Attach to a Transit Gateway

If you see the `Resource Share Not Found` error when attempting to attach to the 
transit gateway:

. Verify that the *ID* and *Owner* values that you specified are correct. 
. Click the pencil icon to edit these values.

Alternatively, remove the transit gateway and re-add it.
See xref:tgw-add-arm.adoc#remove-a-transit-gateway-from-anypoint-platform[Remove a Transit Gateway from Anypoint Platform] and xref:tgw-add-arm.adoc#attach-a-vpc-to-the-transit-gateway[Attach a VPC to the Transit Gateway].


== Unable to Delete a Transit Gateway

If the *Transit Gateways* page doesn't list any VPCs, but you can't delete the transit gateway, the transit gateway might be attached to a VPC that belongs to another business group that you don't have access to.

== Unable to View a Transit Gateway

Runtime Manager always adds transit gateways at the root business group level.
To view a transit gateway, you need CloudHub Network Viewer permission.

== Unable to Modify a Transit Gateway

To modify a transit gateway, you need CloudHub Network Admin permission.

== VPC Attachment Rejected

If you see the `The attachment was rejected in AWS.` error when attempting to attach the VPC to the transit gateway, remove the VPC and re-attach it.

See xref:tgw-add-arm.adoc#detach-an-anypoint-vpc-from-the-transit-gateway[Detach an Anypoint VPC from the Transit Gateway].


== Subnet Already Added to the Route Table

If you see the `This subnet has already been added to this route table.` error, add a different
subnet to the table.

== Invalid CIDR Subnet

If you see the `Please enter a single subnet in CIDR notation.` error, check that the subnet is in the correct CIDR format.

== Failed to Add VPC Route

If you see the `Failed to add VPC route` error from AWS, contact Amazon for details.

== Attach VPC Button is Disabled

If the *Attach VPC* button is disabled, all the VPCs you have access to are already attached to the transit gateway.


== See Also

* xref:tgw-add-arm.adoc#remove-a-route-from-the-transit-gateway-route-table[Remove a Route from the Transit Gateway Route Table]
* xref:tgw-add-arm.adoc#add-routes-to-the-transit-gateway-route-table[Add Routes to the Transit Gateway Route Table]
* xref:tgw-about.adoc#transit-gateway-routing[Transit Gateway Routing]
* https://docs.aws.amazon.com/vpc/latest/tgw/tgw-vpc-attachments.html#transit-gateway-vpc-attch-troubleshooting[Troubleshoot VPC attachment creation] in the AWS documentation
