= To Request VPC Connectivity to Your Network
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you need to connect your VPC to your internal network (VPN tunnel), or to another Cloud network (peering):

. Download link:{attachmentsdir}/VPC-form-v9.3-template.xlsx[the VPC discovery form] (requires at least MS Excel 2007 with macros enabled), and enter the data to communicate the necessary details required for your connectivity method. +
If you need support for multiple Amazon regions, you need to submit one copy of the discovery form for each region in which you need support.
. Contact your MuleSoft account representative to discuss your specific requirements. +
After the CloudHub support team receives your form and answer any remaining questions, they securely exchange keys and supply instructions on how to configure your router(s).

The SLA for configuring VPC is 5 business days after the VPC discovery form has been completed, returned and approved by support, though it may be completed sooner.

== See Also

* xref:vpc-connectivity-methods-concept.adoc[About VPC Connectivity Methods]