= About VPC Firewall Rules
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In CloudHub's default configuration, all applications are hosted in a multi-tenant cloud balanced by a publicly accessible load balancer. +
When creating your own isolated network, you can use your own firewall rules to allow specific IP ranges and ports from reaching your workers.

[NOTE]
====
Keep in mind that the Firewall rules that you configure in your VPC check inbound connections only to your workers, and not to the VPC, your dedicated load balancer or the publicly accessible load balancer.
====

All traffic to your VPC is blocked, unless it's allowed in a firewall rule.
When creating a VPC, 4 firewall rules are created by default:

* 2 rules to allow inbound connections from within your local VPC through ports 8091 and 8092:
+
[source,json,linenums]
----
{
  "CIDR Block": "10.111.0.0/24", // (Local VPC)
  "Protocol": "TCP",
  "From port": 8092,
},

{
  "CIDR Block": "10.111.0.0/24", // (Local VPC)
  "Protocol": "TCP",
  "From port": 8091,
},
----
+
These firewall rules allow traffic from the VPC to reach your workers through ports 8091 and 8092. These are the only ports used by your CloudHub dedicated load balancer to proxy all external communications to your workers through.

* 2 rules to allow inbound connections from anywhere through ports 8081 and 8082:
+
[source,json,linenums]
----
{
  "CIDR Block": "0.0.0.0/0", // (Anywhere)
  "Protocol": "TCP",
  "From port": 8082,
},

{
  "CIDR Block": "0.0.0.0/0", // (Anywhere)
  "Protocol": "TCP",
  "From port": 8081,
}
----
+
[NOTE]
====
These rules allow traffic from any host to reach your workers through ports 8081 and 8082.
These ports are used by CloudHub's shared load balancer to proxy external requests to your workers.
You can remove these rules if you don't want your internal workers to be reached by the publicly accessible load balancer.
====

== See Also

* xref:cloudhub-networking-guide.adoc[Cloudhub Networking Guide]
* xref:dedicated-load-balancer-tutorial.adoc[About Load Balancers (CloudHub)]
* xref:cloudhub-dedicated-load-balancer.adoc[About Cloudhub Dedicated Load Balancer]
* xref:cloudhub-architecture.adoc[CloudHub Architecture]