= About Provisioning a VPC
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Provisioning a VPC for your organization consists of two major steps:

. Create the VPC. +
This is a self-service process. You can create a VPC using either the Runtime Manager UI, or the Anypoint Platform CLI. +
[NOTE]
The Anypoint Platform base subscription includes two VPC licenses, which entitles your Anypoint Platform organization to two VPCs. Once your VPC license limit is reached, the *Create VPC* option is disabled in the user interface.
. Connect to your VPC. +
This must be done by a MuleSoft representative.

[NOTE]
--
To avoid unnecessary downtime, it is critical to define the VPC settings when you first create a new VPC. +
If you edit these settings after the VPC is created, you must then remove all your workers and redeploy them after the change is complete.
--

These settings include:

* The address space for your network. +
This determines the size of your VPC.
* The location of your VPC. +
To enable the VPC to host your workers, it must be bound to a business group and a specific CloudHub region.
+
** The Organization or Business Group for your VPC.
** The CloudHub Region for your VPC.

Read the following FAQs to understand how to plan a successful VPC setup.

== FAQ: How to Calculate VPC and VPN Licensing Requirements

To connect a CloudHub VPC through IPSec VPN, you must have the required number of licenses for your deployment scenario. 

The Anypoint Platform base subscription includes two VPC licenses, which entitles your Anypoint Platform organization to two VPCs. VPN licenses are bundled with the VPC license, so each VPC license also entitles the organisation to one VPN gateway with a connection to one public IP address in a remote location. Therefore, one VPC License = 1 VPC entitlement + 1 VPN entitlement.

An additional VPC license is required for each remote location that needs to be accessible from the CloudHub VPC. 


== FAQ: How to Size my VPC

When you create a VPC, the range of IP addresses for the network must be specified in the form of a Classless Inter-Domain Routing (CIDR) block, using CIDR notation. +
This address space is reserved for Mule workers, so it cannot overlap with any address space used in your data center if you want to peer it with your VPC.

To calculate the proper sizing for your VPC, you first need to understand that the number of dedicated IP addresses is not the same as the number of workers you have deployed. +
For each worker deployed to CloudHub, the following IP assignation takes place:

* For better fault tolerance, the VPC subnet may be divided into up to four Availability Zones.
* A few IP addresses are reserved for infrastructure.
* At least two IP addresses per worker to perform at zero-downtime.

Due to this structure, the smallest network subnet block you can assign for your VPC is /24 and the largest /16. +
A /24 CIDR notation subnet has 256 IP addresses. +
Reserving one IP address for the network and one for broadcast leaves you with 254 hosts for your worker. These get divided into four availability zones of 62 hosts each. Consider that each worker potentially needs two IP addresses for zero downtime, which leaves around 30 IP addresses to assign to your workers. +
Consider also the environments required in a VPC.  For example, if you need space for 300 instances each in Dev, QA, and UAT, you need to size for 1024 instances at minimum.

The safe rule of thumb for deciding the size of your VPC subnet is to calculate 10 times the maximum number of expected apps to deploy in the VPC.

== FAQ: Where To Place a VPC Inside my Organization

As an organization administrator, you can create a VPC and share it with any business group within your main organization. +
However, once the VPC is inherited by a business group, only the administrator of said business group can operate the VPC. For example, a CloudHub organization administrator or a business group owner can create or update an existing VPC (owned or inherited) to make it the default for either the region, the environment, or both. +
However, if such an association already exists, it's overwritten by the requested VPC.

If no business group association is specified, or if your organization does not have any business groups, the VPC ownership remains associated with the main organization. The organization under which the VPC is created is the VPC owner and this organization's administrator is the only one who can share the VPC. +
VPCs can only be shared vertically from the main organization to one of its business groups, or from a business group to one of its child business groups. +
You cannot share a VPC created by a business group with another business group that is higher in the hierarchy.

It is recommended that you create your VPC in your master organization, and share it with the other business groups.

== FAQ: Which Region to use When Creating a VPC

You can create your VPC inside any of the available CloudHub regions. +
The recommended region to use might vary depending on how you connect to your VPC. If you are using a VPN tunnel, you might want to choose the CloudHub region closest to your data center. +
However, if you are peering with your private AWS VPC, you need to create your CloudHub VPC in the same AWS region.

== See Also

* xref:to-request-vpc-connectivity.adoc[To Request VPC Connectivity to Your Network]
