= Anypoint VPN
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Anypoint VPN feature enables you to create a secure connection to systems within your network that are hosted outside of Anypoint Platform. If required, you can create multiple VPNs to connect to different networks or different regions within a network.

[NOTE]
The number of VPNs you can create depends on the VPN capacity allocated to your account.

To create and maintain a secure connection with your external network, the Anypoint VPN provides the following features:

* Route-based access via 2-byte and 4-byte Autonomous System Numbers (ASN). This defines the routing policies used to connect to your network through the VPN.
* Reusable IP addresses.
* Tunnel configuration.

[NOTE]
Network Address Translation (NAT) is not supported.

== Supported IPSEC Configurations

Anypoint VPN supports the IPSEC configurations for encrypting data communications between Anypoint Platform and your network:

* IKE version 1
* AES 128 and 256-bit encryption
* SHA and SHA-2 hashing
* Diffie-Hellman (DH) groups:
** Phase1 DH groups 2, 14-18, 22, 23, 24
** Phase2 DH groups 2, 5, 14-18, 22, 23, 24

[NOTE]
Anypoint VPN only supports acting as a responder, so IPSEC connections should be brought up and maintained up by initiating traffic from a remote device.

== Anypoint VPN Routing

The Anypoint VPN supports two types of routing:

* Border Gateway Protocol (BGP) routing: Enables you to use dynamic routing. This allows the device you are connecting to broadcast routes to the VPN. We recommend using BGP routing if your device supports this protocol.
* Static routing: Requires you to specify the routes that the Anypoint VPN uses to communicate with your network.

== See Also

xref:vpn-create-arm.adoc#vpn-create-arm[Create a CloudHub VPN from Runtime Manager]
