= Anypoint VPN
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Anypoint VPN feature enables you to create a secure connection to systems within your network that are hosted outside of Anypoint Platform. If required, you can create multiple VPNs to connect to different networks or different regions within a network.

[NOTE]
The number of VPNs you can create depends on the VPN capacity allocated to your account.

To create and maintain a secure connection with your external network, the Anypoint VPN provides the following features:

* Route-based access via 2-byte and 4-byte Autonomous System Numbers (ASN). This defines the routing policies used to connect to your network through the VPN.
* Reusable IP addresses.
* Tunnel configuration.

[NOTE]
Network Address Translation (NAT) is not supported.

== Supported IPsec Configurations

Anypoint VPN supports the IPsec configurations for encrypting data communications between Anypoint Platform and your network:

* IKE version 1
* AES 128 and 256-bit encryption
* SHA and SHA-2 hashing
* Diffie-Hellman (DH) groups:
** Phase1 DH groups 2, 14-18, 22, 23, 24
** Phase2 DH groups 2, 5, 14-18, 22, 23, 24

[NOTE]
The Anypoint VPN endpoint is the responder, so you should establish and maintain connections by initiating traffic from a remote device.

== Anypoint VPN Routing

The Anypoint VPN supports two types of routing:

* Border Gateway Protocol (BGP) routing - Your device uses BGP to dynamically advertise its routes to Anypoint VPN. BGP routing is recommended if your device supports this protocol.
* Static - Requires you to specify the routes (subnets) for your network that should be accessible to Anypoint VPN.

== Tested Network Devices

The following table lists the network devices that are known to work with the Anypoint VPN.

[%header%autowidth.spread]
|===
|Hardware | Software
|Check Point Security Gateway | R77.10 or later
|Cisco ASA | ASA 8.2 or later
|Cisco IOS | Cisco IOS 12.4 or later
|Dell SonicWALL | SonicOS 5.9 or later
|Fortinet Fortigate 40+ Series | FortiOS 4.0 or later
|Juniper J-Series Service Router | JunOS 9.5 or later
|Juniper SRX-Series Services Gateway | JunOS 11.0 or later
|Juniper SSG | ScreenOS 6.1 or 6.2 or later
|Juniper ISG | ScreenOS 6.1 or 6.2 or later
|Netgate pfSense | OS 2.2.5 or later
|Palo Alto Networks | PANOS 4.1.2 or later
|Yamaha RT107e, RTX1200, RTX1210, RTX1500, RTX3000 and SRT100 routers | 
|Microsoft Windows Server | 2008 R2 or later +
2012 R2 or later
|Zyxel Zywall Series | 4.20 or later for statically routed VPN connections +
4.30 or later for dynamically routed VPN connections
|===

== See Also

xref:vpn-create-arm.adoc#vpn-create-arm[Create a CloudHub VPN from Runtime Manager]
