# Vale configuration file for docs-runtime-manager

StylesPath = .vale/styles
MinAlertLevel = suggestion
Vocab = technical, product

[*.adoc]
BasedOnStyles = Vale

# Ignore certain patterns
*.{png,jpg,jpeg,gif,svg} = skip
*node_modules* = skip
*.graffle = skip
*.xlsx = skip