site:
  title: Runtime Manager Docs
content:
  sources:
    - url: .
      start_path: cloudhub
      branches: [HEAD]
    - url: .
      start_path: runtime-manager
      branches: [HEAD]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
