= Transit Gateway Attachments
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::tgw-about.adoc,


AWS Transit Gateway acts as a cloud router in AWS, simplifying network access between VPCs,
on-premises data centers, and third-party software, while providing increased visibility and control over the network.
Transit gateways effectively merge your organization’s cloud resources and on-premises datacenters
into one network topology.

On CloudHub, you can take advantage of this network simplification by securely attaching Anypoint Virtual Private Cloud (VPC)
to AWS Transit Gateway in your AWS account.

You can add multiple transit gateways to your Anypoint Platform organization.
The number of transit gateways you can add depends on the network connection entitlements available to your account.
Contact your MuleSoft account representative if you don't know how many entitlements are associated with your account.

== Limitations

The following values are governed by AWS limits:

* Maximum number of transit gateways per VPC
* Maximum number of VPCs that you can attach to a transit gateway

For information about limitations when attaching a VPC to an AWS transit gateway,
see
https://docs.aws.amazon.com/vpc/latest/tgw/tgw-vpc-attachments.html[Transit gateway attachments to a VPC^] in the AWS documentation.

== See Also

* xref:tgw-attach-arm.adoc[Attach to Transit Gateways]
* https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html[What is a transit gateway?^] in the AWS documentation
* https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html[Transit gateway route tables^] in the AWS documentation
