= Request Anypoint VPC Connectivity to Your Network
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::to-request-vpc-connectivity.adoc,


The process for requesting or updating Anypoint Virtual Private Cloud (Anypoint VPC) connectivity to your network depends on the connectivity method you use: IPsec, transit gateway attachments, VPC peering, or AWS Direct Connect.

[NOTE]
The SLA for provisioning an Anypoint VPC connection is five business days after MuleSoft Support receives and approves your completed Anypoint VPC discovery form.


== Configure IPsec VPN Connections

As of November 2018, MuleSoft Support no longer creates new VPN connections.
For all new VPNs, you must follow the self-service steps in xref:vpn-create-arm.adoc[Create an Anypoint VPN].

To update _existing_ IPsec VPN connections that were created by MuleSoft Support before November 2018:

. Download the link:assets/attachments/VPC-form-v9.5-template.xlsx[Anypoint VPC discovery form].
+
This form requires Microsoft Excel 2007 or later (with macros enabled).
. For each VPC connection to update, complete and submit a separate Anypoint VPC form:
.. Complete all fields in the *Overview* and *IPSec* tabs.
+
To avoid processing delays, ensure that you complete all fields on both tabs.
.. Open a Support ticket and submit your completed form.

The MuleSoft Support team updates the VPN configuration using the details provided in the Anypoint VPC discovery form.
Support updates your ticket to notify you when your request is complete.

== Configure Transit Gateway Attachments

To configure transit gateway attachments, follow the self-service steps in xref:tgw-attach-arm.adoc[Attach to Transit Gateways].

== Configure VPC Peering Connections

Because MuleSoft does not support inter-region peering, both VPCs must reside in the same region.

To request new or update existing VPC peering connections:

. Download the link:assets:attachments::VPC-form-v9.5-template.xlsx[Anypoint VPC discovery form].
+
This form requires Microsoft Excel 2007 or later (with macros enabled).
. For each VPC peering connection, complete and submit a separate Anypoint VPC form.
+
You must complete the Anypoint VPC discovery form for both new connections and for updates to existing configurations.

.. Complete all fields in the *Overview* and *VPC Peering* tabs.
+
To avoid processing delays, ensure that you complete all fields on both tabs.
.. Open a Support ticket and submit your completed form.


The MuleSoft Support team creates or updates the VPC peering connection request using the details provided in the Anypoint VPC discovery form.
Support updates your ticket to notify you when your request is complete.

== Configure Direct Connect Connections

To request new or update existing Direct Connect (DX) connections:

. Establish DX connections to your AWS account or your partner's AWS account.
. Create either a virtual interface (VIF) or a hosted connection with the MuleSoft Account ID.
. Download the xref:attachments::VPC-form-v9.5-template.xlsx[Anypoint VPC discovery form].
+
This form requires Microsoft Excel 2007 or later (with macros enabled).
. For each DX connection, complete and submit a separate Anypoint VPC form.
+
You must complete the Anypoint VPC discovery form for both new connections and updates to existing configurations.

.. Complete all fields in the *Overview* and *Direct Connect* tabs.
+
To avoid processing delays, ensure that you complete all fields on both tabs.
.. Open a Support ticket and submit your completed form.

The MuleSoft Support team accepts the VIF or connection request.
Support updates your ticket to notify you when your request is complete.


== See Also

* xref:vpc-connectivity-methods-concept.adoc[Anypoint VPC Connectivity Methods]
* xref:vpn-about.adoc[Anypoint VPN]
