= Generate Apps Diagnostics and Analyze with Einstein

You can generate diagnostics for your CloudHub apps and run an AI-powered analysis with Einstein. Use one of these options:

* xref:#download-diagnostics[Download diagnostics from Runtime Manager]
* xref:#run-diagnostics-with-url[Download diagnostics via URL]
* xref:#run-the-mulesoft-diagnostics-agent[Generate diagnostics with MuleSoft Diagnostics Agent]

== Understanding Diagnostics

Diagnostics are snapshots of your app at a point in time. They include a Java thread dump for each worker (all threads and their state), which helps with debugging and support. For supported Mule versions, diagnostics also include the Diagnostic Information Analysis File (DIAF), which Einstein uses for analysis.

Diagnostics aren't available for apps on Mule versions earlier than 3.8.0 (excluding 3.7.4).

include::cloudhub-2::partial$diagnostics-agent.adoc[tag=diafFile]

DIAF is available for applications running on these Mule versions:

* 4.6.23 and later 4.6.x versions
* 4.9.10 and later 4.9.x versions
* 4.10.x and later

Without DIAF, CloudHub gives you a text file: `__appName__-instance-__instanceId__-__workerNumber__-diag.txt`. When DIAF is included, you get a `.zip` file instead. Open the file in a text editor or unzip the archive as needed.

[[download-diagnostics]]
== Download Diagnostics from Runtime Manager

To download diagnostics from Runtime Manager:

. In the *Deployments* section, select the date and worker for which you want to download diagnostics.
. Click the download icon for the worker.
. Select *Diagnostics*.

You can then xref:#analyze-diagnostics-with-einstein[analyze the diagnostics with Einstein].

[[run-diagnostics-with-url]]
== Download Diagnostics via URL

To download a diagnostics file directly, use this URL. Replace `__appName__` with your application name and `__instanceId__` with the instance ID (you can find both in Runtime Manager).

`api/v2/applications/__appName__/instances/__instanceId__/diagnostics`


[[run-the-mulesoft-diagnostics-agent]]
== Generate Diagnostics with MuleSoft Diagnostics Agent

On the Runtime Manager *Diagnostics* page, you run the MuleSoft Diagnostics Agent to generate diagnostics on demand for a chosen replica. You can then download the diagnostics for manual inspection, or *Analyze with Einstein* (or both). 

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Select the app name.
. In the navigation menu, select *Diagnostics*.
. Select an active replica from the dropdown list.
. Click the *Analyze & Troubleshoot* dropdown. You have these options:
** Select *Generate Mule Diagnostics* to generate and download the diagnostics for manual inspection.
... Click *Download* to download the Mule diagnostics files.
** Select *Analyze with Einstein* to generate the Mule diagnostics and run the analysis simultaneously.
... Click *View Analysis* to open the analysis page.

=== Generate Mule Diagnostics

When you choose *Generate Mule Diagnostics* and click *Download*, you get a `.zip` file. The archive contains:

Mule Thread Dumps::
+
A thread dump is a snapshot of all the threads in a replica that shows the current state of the server.

Diagnostic Information Analysis File (DIAF)::
+
include::partial$diagnostics-agent.adoc[tag=diafFile]
+
[NOTE]
The DIAF doesn't replace application logs.

[[analyze-diagnostics-with-einstein]]
== Analyze Diagnostics with Einstein

In Runtime Manager, you can run *Analyze with Einstein* for a specific worker. The platform uses your diagnostics and the DIAF to produce an analysis that suggests root causes and recommended actions. You download the result as an HTML file.

=== Before You Analyze

Before analyzing diagnostics with Einstein:

include::cloudhub-2::partial$diagnostics-agent.adoc[tag=prerequisites]

=== Run Analyze with Einstein

To run and download the Einstein analysis:

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Select the app name.
. In the navigation menu, select *Logs*.
. In the *Deployments* section, select the date and worker for which you want to run the analysis.
. Click the download icon for the worker and select *Analyze with Einstein*.
. After the process completes, click the download icon to download an `.html` file containing the analysis.

== Considerations and Limitations

include::cloudhub-2::partial$diagnostics-agent.adoc[tag=considerationsLimitations]

CloudHub retains Mule diagnostics for 30 days or up to 150 MB.

== See Also

* xref:mule-runtime::mule-troubleshooting-plugin.adoc#understanding-diagnostic-information-analysis-file-diaf[Understanding Diagnostic Information Analysis File (DIAF)]
* xref:viewing-log-data.adoc[View Log Data]
* xref:runtime-manager::sending-data-from-arm-to-external-analytics-software.adoc[Export Data to External Analytics Tools]
* xref:runtime-manager::monitoring.adoc[Monitor Applications and Servers]
* xref:runtime-manager::deployment-strategies.adoc[Deployment Options]
