= Collect Apps Diagnostics and Analyze with Einstein

Troubleshoot CloudHub applications by downloading comprehensive diagnostics files. Use Einstein generative AI to automatically analyze diagnostics and receive intelligent insights about root causes and recommended actions. This analysis identifies performance issues, memory problems, and configuration errors to help resolve problems faster.

== Before You Begin

Before analyzing MuleSoft diagnostics with Einstein:

include::cloudhub-2::partial$diagnostics-agent.adoc[tag=prerequisites]

== Download Diagnostics

Diagnostics display the Java thread dump of each CloudHub worker in each deployment. These indicate the current state of the server, which is helpful for debugging and support.

Diagnostics aren't available for apps running on Mule versions earlier than 3.8.0 (excluding version 3.7.4).

CloudHub downloads the diagnostic output to a text file in the format `__appName__-instance-__instanceID__-__workerNumber__-diag.txt`.
Use a text editor to view the diagnostics file.

CloudHub Diagnostics includes the Diagnostic Information Analysis File (DIAF).

include::cloudhub-2::partial$diagnostics-agent.adoc[tag=diafFile]

This capability is available for applications running on these Mule versions:

* 4.6.23 and later 4.6.x versions
* 4.9.10 and later 4.9.x versions
* 4.10.x and later

CloudHub downloads the diagnostic output, including the DIAF, to a `.zip` file. 

To download diagnostics:

. In the *Deployments* section, select the date and worker for which you want to download diagnostics.
. Click the download icon for the worker and select *Diagnostics*.


[TIP]
====
You can also use the following URL to download a diagnostics file directly:

`api/v2/applications/__appName__/instances/__instanceId__/diagnostics`
====

[[run-the-mulesoft-diagnostics-agent]]
== Run the MuleSoft Diagnostics Agent

You can also run the MuleSoft Diagnostics Agent from Runtime Manager to generate and download the diagnostics for manual inspection or to run the analysis simultaneously.

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Select the app name.
. In the navigation menu, select *Diagnostics*.
. Select an active replica from the dropdown list.
. Click the *Analyze & Troubleshoot* dropdown. You have these options:
** Select *Generate Mule Diagnostics* to generate and download the diagnostics for manual inspection.
... Click *Download* to download the Mule diagnostics files.
** Select *Analyze with Einstein* to generate the Mule diagnostics and run the analysis simultaneously. 
... Click *View Analysis* to open the analysis page.

=== Generate Mule Diagnostics
If you download the generated Mule diagnostics, you receive a `.zip` archive containing two key assets:

Mule Thread Dumps::
+
A thread dump is a snapshot of all the threads in a replica that shows the current state of the server.

Diagnostic Information Analysis File (DIAF)::
+
include::partial$diagnostics-agent.adoc[tag=diafFile]
+
[NOTE]
The DIAF doesn’t replace application logs.

=== Analyze with Einstein
If you select *Analyze with Einstein*, the system generates the Mule diagnostics and runs the Einstein analysis simultaneously. The resulting analysis identifies root causes and recommends actions based on the DIAF file.


== Considerations and Limitations

include::cloudhub-2::partial$diagnostics-agent.adoc[tag=considerationsLimitations]

CloudHub retains Mule diagnostics for 30 days or up to 150 MB.

== See Also

* xref:mule-runtime::mule-troubleshooting-plugin.adoc#understanding-diagnostic-information-analysis-file-diaf[Understanding Diagnostic Information Analysis File (DIAF)]
* xref:viewing-log-data.adoc[View Log Data]
* xref:runtime-manager::sending-data-from-arm-to-external-analytics-software.adoc[Export Data to External Analytics Tools]
* xref:runtime-manager::monitoring.adoc[Monitor Applications and Servers]
* xref:runtime-manager::deployment-strategies.adoc[Deployment Options]
