= CloudHub Load Balancers
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::dedicated-load-balancer-tutorial.adoc
:page-notice-banner-message: <p>Support for TLS 1.1 and earlier ends soon. For <b>Dedicated Load Balancers (DLBs)</b>, support ends on <b>October 2, 2025</b> for new DLBs and on <b>January 31, 2026</b> for existing DLBs.<br/>For <b>CloudHub Shared Load Balancers (SLBs)</b>, support ends on <b>October 17, 2025</b>. Update your DLB and SLB configurations to use <b>TLS 1.2 or later</b> to prevent service interruptions.</p>

CloudHub provides two types of load balancers:

* Shared Load Balancer
+
Provides basic load balancing functionality.
* Dedicated Load Balancer
+
Enables you to deploy and configure one or more custom load balancers within an Anypoint Virtual Private Cloud (Anypoint VPC).

== Shared Load Balancers

CloudHub provides a default shared load balancer that is available in all environments. The shared load balancer provides basic functionality, such as TCP load balancing. 

Shared load balancers don't allow you to configure custom SSL certificates or proxy rules. The shared load balancer has its own SSL certificate. If you use the shared load balancer to access your application, the system uses this certificate. If you access your application directly, the system uses the SSL certificate configured in the application.

Additionally, shared load balancers have lower rate limits that help ensure platform stability. MuleSoft regularly monitors and scales these limits as necessary. Rate limits on shared load balancers are applied according to region. If you're deploying an application to workers in multiple regions, the rate limit for each region can be different.

If an application exceeds the rate limit for a shared load balancer, the load balancer returns a 429 Service Unavailable response.

To perform custom load balancer configuration or have higher rate limit thresholds, you must use a dedicated load balancer.

The shared load balancer supports TLS 1.2.

== Dedicated Load Balancers

Dedicated load balancers enable you to:

* Handle load balancing among the different CloudHub workers that run your application.
* Define SSL configurations to provide custom certificates and optionally enforce two-way SSL client authentication.
* Configure proxy rules that map your applications to custom domains.
+
This enables you to host your applications under a single domain.
* Enable HTTP Streaming via the API in CloudHub.
+
[NOTE]
The uploaded file size cannot be over 1000MB.

Dedicated load balancers are an optional component of Anypoint Platform.

For information about dedicated load balancers, see xref:cloudhub-dedicated-load-balancer.adoc[Dedicated Load Balancers].

[NOTE]
CloudHub load balancers use Nginx HTTP server capabilities. Nginx reverse proxies ignore HTTP header fields with invalid names. Valid HTTP header names are composed of English letters, numbers, hyphens, and underscores. Only valid headers are forwarded to the Mule application. Use only valid header names to avoid any issues. This applies to both shared and dedicated load balancers.

== See Also

* xref:index.adoc[CloudHub]
* xref:virtual-private-cloud.adoc[Virtual Private Cloud]
* xref:lb-architecture.adoc[Dedicated Load Balancer Architecture]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/[CloudHub API^]
* https://help.mulesoft.com/s/article/How-to-Enable-DLB-Streaming-Feature-via-the-API-in-Cloudhub-1-0[How to Enable DLB Streaming Feature via the API in CloudHub^]
