= Create a Load Balancer with the Anypoint Platform CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::lb-create-cli.adoc



You can create a dedicated load balancer (DLB) using the Anypoint Platform CLI.


== Prerequisites

Before you create a load balancer:

* Ensure that you are an administrator in the organization where you are creating the DLB.
* Create an Anypoint Virtual Private Cloud (Anypoint VPC) instance in the organization where you want to create a DLB.
* Create at least one certificate and private key for your certificate.

== Create a Load Balancer Using the CLI

Use this command to create a DLB from the CLI:

[source,linenums]
----
cloudhub load-balancer create myVPC myLB_name certificateName privateKey
----

This command specifies the Anypoint VPC instance _myVPC_ in which to create the DLB and the _certificateName_ and _privateKey_ that the DLB uses.

//NO RENAME SHARED
include::partial$no-rename.adoc[tag=noRenameDLB]

The CloudHub DLB name cannot start with `internal-`. 

== See Also

* xref:cloudhub-cli.adoc#cloudhub-load-balancer-create[cloudhub load-balancer create]
* xref:cloudhub-cli.adoc#cloudhub-load-balancer-ssl-endpoint-add[cloudhub load-balancer ssl-endpoint add]
* xref:cloudhub-cli.adoc#cloudhub-load-balancer-ssl-endpoint-set-default[cloudhub load-balancer ssl-endpoint set-default]
* xref:lb-cert-upload.adoc[Add Certificates to a Dedicated Load Balancer]
* xref:access-management::index.adoc[Access Management]
