= Create a Load Balancer with Runtime Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::lb-create-arm.adoc
:page-notice-banner-message: Support for TLS 1.1 and earlier versions in Dedicated Load Balancers (DLB) ends soon. For new DLBs, support for TLS 1.1 and earlier versions ends on <b>December 1, 2025</b>. For existing DLBs, support for TLS 1.1 and earlier versions ends on <b>October 31, 2026</b>. Update your DLB configuration to use TLS 1.2 or a later version to prevent service interruptions.




You can use Runtime Manager to create a dedicated load balancer (DLB) in your CloudHub environment.

== Prerequisites

Before creating a load balancer, perform the following:

* Ensure that your profile is authorized to perform this action by adding the *CloudHub Network Administrator* permission to the profile of the organization where you are creating the load balancer.
+
Similarly, the administrator role of the same organization also provides the authorization required.
* Create an Anypoint Virtual Private Cloud (Anypoint VPC) in the organization where you want to create a load balancer.
* Create at least one certificate and private key for your certificate.

== Create a Load Balancer

. From Anypoint Platform, click *Runtime Manager*.
. Click *Load Balancers* > *Create Load Balancer*.
. Enter a name for your load balancer.
+
The CloudHub DLB name must be unique across all DLBs defined in Anypoint Platform (by all MuleSoft customers).
For this reason, you might want to append your organization name to your DLB name.
+
//NO RENAME SHARED
include::partial$no-rename.adoc[tag=noRenameDLB]
+
Each dedicated load balancer exposes an external domain `_lb-name_.lb.anypointdns.net` name where `_lb-name_` is the name you provide.
+
The CloudHub DLB name cannot start with `internal-`.

. Select a target Anypoint VPC from the drop-down list.
. Specify the amount of time the DLB waits for a response from the Mule application in the *Timeout in Seconds* field.
+
The default value is 300 seconds.

. Add any allowlisted classless inter-domain routing (CIDR) as required.
+
The IP addresses you specify here are the only IP addresses that can access the load balancer. The default value is `0.0.0.0/0`.

. Select the inbound HTTP mode for the load balancer.
+
This property specifies the behavior of the load balancer when receiving an HTTP request. Valid values are:
+
* *Off*
+
Causes the load balancer to silently drop the request.
* *On*
+
Accepts the inbound request on the default SSL endpoint using the HTTP protocol.
* *Redirect*
+
Redirects the request to the same URL using the HTTPS protocol.
. Specify options:
+
* *Enable Static IPs* specifies to use static IPs, which persist when the DLB restarts.
+
For more information about static IP addresses, see xref:cloudhub-dedicated-load-balancer.adoc#static-ip-addresses[Static IP Addresses].
* *Keep URL encoding* specifies that the DLB passes only the `%20` and `%23` characters as is.
+
If you deselect this option, the DLB decodes the encoded part of the request URI before passing it to the CloudHub worker.
* *Transport Downstream Protocols* specifies the list of enabled TLS protocols for connections from the client to the DLB.
+
Use the dropdown to add or remove protocols.
* *Transport Upstream Protocols* specifies the list of enabled TLS protocols for connections from the DLB to the Mule application.
+
Use the dropdown to add or remove protocols.
* *Forward Client Certificate* specifies that the DLB forwards the client certificate to the CloudHub worker.
. Add a certificate.

.. Click *Add certificate*:
.. On the *Create Load Balancer | Add certificate* page, select *Choose File* to upload both public key and private key files.
.. If you want to add a trusted CA certificate, click *Choose File* to upload the file.
+
The trusted CA certificate is used to verify client certificates.

.. If you want to add URL mapping rules, click the *>* icon to display the options:
+
If you add more than one URL mapping rule, order the rules in the list according to the priority in which they should be applied.
+
Click *Add New Rule*, and then specify the input path, target app, output path, and protocol.
.. Click *Save Certificate*.
. Click *Create Load Balancer*.


== See Also

* xref:access-management::index.adoc[Access Management]
* xref:cloudhub-dedicated-load-balancer.adoc[Dedicated Load Balancers]
* xref:lb-cert-upload.adoc[Add Certificates to a Dedicated Load Balancer]
* xref:lb-cert-validation.adoc[Certificate Validation in Dedicated Load Balancers]
* xref:lb-allowlists.adoc[Allowlists]
* xref:lb-mapping-rules.adoc[Mapping Rules]
