= Create a Load Balancer with the CloudHub API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::lb-create-api.adoc


You can create a dedicated load balancer (DLB) using the CloudHub API.

== Prerequisites

To create a load balancer using the CloudHub API, ensure that you perform the following:

* Ensure that you are an administrator in the organization where you are creating the load balancer.
* Create an Anypoint Virtual Private Cloud (Anypoint VPC) in the organization where you want to create a load balancer.
* Create at least one certificate and private key for your certificate.

== Create a Load Balancer

To create a load balancer using the CloudHub API, use the following endpoints:

* `anypoint.mulesoft.com/cloudhub/api/organizations/_orgid_/loadbalancers`
* `anypoint.mulesoft.com/cloudhub/api/organizations/_orgid_/vpcs`

//NO RENAME SHARED
include::partial$no-rename.adoc[tag=noRenameDLB]

The CloudHub DLB name cannot start with `internal-`. Starting the DLB name with `internal-` results in error message: `LB name=internal-dlb-name cannot start with -internal`.

== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/1.0.13/console/method/%233964/[CloudHub API Create New Load Balancer]
* xref:access-management::index.adoc[Access Management]
* xref:lb-cert-upload.adoc[Add Certificates to a Dedicated Load Balancer]
* xref:lb-cert-validation.adoc[Certificate Validation in Dedicated Load Balancers]
