= Maintenance and Upgrade Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::maintenance-and-upgrade-policy.adoc


All maintenance to the Runtime Manager console, platform services, and worker cloud (see xref:cloudhub-architecture.adoc[CloudHub Architecture]) is performed during the maintenance windows specified in the https://status.salesforce.com/products/Mulesoft[Status] page, except for critical security issues, which are fixed immediately.

MuleSoft policy is to perform all maintenance transparently and without any downtime to your integrations running in the worker cloud wherever possible. In cases where downtime for the console, platform services, or workers is unavoidable, MuleSoft communicates these maintenance windows at least eight hours in advance and typically seven days in advance, with the exception of critical security patches, which might be fixed immediately.

View the current status and detailed service history for the Runtime Manager console, CloudHub platform services, and the CloudHub worker cloud:

* US: https://status.salesforce.com/products/Mulesoft/[status.mulesoft.com]
* EU: https://status.salesforce.com/products/Mulesoft[eu1-status.mulesoft.com]
* MuleSoft Government Cloud: https://status.salesforce.com/products/Mulesoft[gov-status.mulesoft.com]


== See Also

* https://www.salesforce.com/en-us/wp-content/uploads/sites/4/documents/legal/Agreements/versioning-back-support-policy.pdf[Product Versioning and Back Support Policy]
